version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    # env_file:
    #   - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    networks:
      - chucks

  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog
    networks:
      - chucks
networks:
  chucks:
